"""Browser smoke test against scripts/ui_fixture.py on port 18317."""
from pathlib import Path
import json
import os
import socket
import tempfile
from playwright.sync_api import sync_playwright, expect

output = Path(__file__).resolve().parents[1] / ".clash-tokens" / "ui-artifacts"
output.mkdir(parents=True, exist_ok=True)
with tempfile.TemporaryDirectory(prefix="cot-browser-test-") as profile_dir, sync_playwright() as playwright:
    with socket.socket() as listener:
        listener.bind(("127.0.0.1", 0))
        browser_port = listener.getsockname()[1]
    browser = playwright.chromium.launch_persistent_context(profile_dir, headless=True, args=[f"--remote-debugging-port={browser_port}"], viewport={"width": 1440, "height": 1000})
    browser.add_cookies([{"name":"session", "value":"synthetic-browser-secret", "url":"https://www.doubao.com/"}, {"name":"unrelated", "value":"unrelated-secret", "url":"https://example.org/"}])
    page = browser.new_page()
    errors = []
    page.on("pageerror", lambda error: (errors.append(str(error)), print("Browser error:", error)))
    page.goto("http://127.0.0.1:18317")
    page.wait_for_load_state("networkidle")
    expect(page.get_by_role("heading", name="Your sources, one place.")).to_be_visible()
    page.get_by_label("Admin key", exact=True).fill("ui-test-admin-key-123456789")
    page.get_by_role("button", name="Connect", exact=True).last.click()
    expect(page.get_by_role("heading", name="Overview", exact=True)).to_be_visible()
    expect(page.get_by_role("heading", name="Workload and memory", exact=True)).to_be_visible()
    expect(page.get_by_role("cell", name="Routing queued / limit", exact=True)).to_be_visible()
    expect(page.get_by_role("cell", name="Go heap allocated", exact=True)).to_be_visible()
    page.screenshot(path=str(output / "overview.png"), full_page=True)
    page.get_by_role("link", name="Providers", exact=True).click()
    expect(page.get_by_role("heading", name="Providers", exact=True)).to_be_visible()
    page.get_by_role("searchbox", name="Filter providers").fill("openai")
    page.get_by_role("button", name="openai", exact=True).click()
    expect(page.get_by_role("heading", name="openai", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add account", exact=True).click()
    page.get_by_label("ID", exact=True).fill("ui-account")
    page.get_by_label("Display Name", exact=True).fill("UI test account")
    page.get_by_label("Quota domain", exact=True).fill("ui-quota")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    auth_status = {"claude-web": 200, "blackbox": 200}
    auth_requests = []
    existing_browser_pages = len(browser.pages)
    def synthetic_auth(route):
        adapter = "claude-web" if route.request.url.startswith("https://claude.ai/") else "blackbox"
        auth_requests.append((adapter, route.request.method, route.request.url))
        assert route.request.method == "GET", "Login check performed a write"
        endpoint = "/api/organizations" if adapter == "claude-web" else "/api/auth/session"
        if route.request.url.endswith(endpoint):
            payload = [{"uuid":"private-organization-id"}] if adapter == "claude-web" else {"user":{"email":"private@example.test"}, "accessToken":"private-session-token"}
            route.fulfill(status=auth_status[adapter], content_type="application/json", body=json.dumps(payload))
        else:
            route.fulfill(status=200, content_type="text/html", body='<html><body><div contenteditable="true" style="width:300px;height:60px"></div></body></html>')
    browser.route("https://claude.ai/**", synthetic_auth)
    browser.route("https://app.blackbox.ai/**", synthetic_auth)
    page.get_by_role("link", name="Accounts", exact=True).click()
    expect(page.get_by_text("UI test account", exact=True)).to_be_visible()
    page.get_by_role("link", name="Browsers", exact=True).click()
    page.get_by_role("button", name="Add profile", exact=True).click()
    page.get_by_label("ID", exact=True).fill("ui-profile")
    page.get_by_role("dialog").get_by_label("Browser connection URL", exact=True).fill(f"http://127.0.0.1:{browser_port}")
    page.get_by_role("button", name="Review changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("ui-profile", exact=True)).to_be_visible()
    page.get_by_role("link", name="Credentials", exact=True).click()
    expect(page.get_by_role("heading", name="Credentials", exact=True)).to_be_visible()
    page.get_by_role("button", name="Import browser cookies", exact=True).click()
    page.get_by_label("Configured browser profile", exact=True).select_option("ui-profile")
    page.get_by_label("Provider", exact=True).select_option("doubao")
    page.get_by_role("button", name="Preview cookies", exact=True).click()
    expect(page.get_by_text("www.doubao.com: 1 cookies", exact=True)).to_be_visible()
    assert "synthetic-browser-secret" not in page.content()
    assert "unrelated-secret" not in page.content()
    page.get_by_role("button", name="Save cookies", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("browser:ui-profile:doubao", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add credential", exact=True).click()
    page.get_by_label("Credential ID", exact=True).fill("ui-token")
    page.get_by_label("Secret value", exact=True).fill("synthetic-secret-not-for-display")
    page.get_by_role("button", name="Save credential", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("cred://ui-token", exact=True)).to_be_visible()
    assert "synthetic-secret-not-for-display" not in page.content(), "Credential echoed into DOM"
    page.get_by_role("button", name="Import export", exact=True).click()
    page.get_by_label("CSV or JSON file", exact=True).set_input_files({"name":"selected.csv","mimeType":"text/csv","buffer":b"name,url,username,password\nSelected,https://example.com,synthetic-login,synthetic-import-secret\nSkipped,https://example.org,other-user,other-secret\n"})
    page.get_by_role("button", name="Preview entries", exact=True).click()
    expect(page.get_by_role("heading", name="Select credentials to import", exact=True)).to_be_visible()
    assert "synthetic-import-secret" not in page.content()
    assert "synthetic-login" not in page.content()
    page.get_by_role("checkbox", name="Import entry 1", exact=True).check()
    page.get_by_role("button", name="Import selected", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("selected-export", exact=True)).to_have_count(1)
    assert "synthetic-import-secret" not in page.content()
    page.get_by_role("button", name="Import export", exact=True).click()
    page.get_by_label("Export format", exact=True).select_option("bitwarden-json")
    page.get_by_label("CSV or JSON file", exact=True).set_input_files({"name":"bitwarden.json","mimeType":"application/json","buffer":b'{"items":[{"type":1,"name":"Manager login","login":{"username":"hidden-user","password":"hidden-manager-secret","uris":[{"uri":"https://example.com"}]}},{"type":2,"name":"Note","notes":"hidden-note"}]}'})
    page.get_by_role("button", name="Preview entries", exact=True).click()
    expect(page.get_by_text("Skipped 1 non-web or non-password records.", exact=False)).to_be_visible()
    assert "hidden-manager-secret" not in page.content()
    assert "hidden-note" not in page.content()
    page.get_by_role("checkbox", name="Import entry 1", exact=True).check()
    page.get_by_role("button", name="Import selected", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("selected-export", exact=True)).to_have_count(2)
    page.get_by_role("link", name="Accounts", exact=True).click()
    expect(page.get_by_role("heading", name="Accounts", exact=True)).to_be_visible()
    page.get_by_role("button", name="Discover candidates", exact=True).click()
    page.get_by_role("dialog").get_by_role("button", name="Discover", exact=True).click()
    expect(page.get_by_role("heading", name="Account discovery", exact=True)).to_be_visible()
    expect(page.get_by_role("cell", name="password_managers", exact=True)).to_be_visible()
    expect(page.get_by_text("chat.openai.com", exact=True)).to_have_count(0)
    assert "synthetic-import-secret" not in page.content()
    page.get_by_role("button", name="Open accounts", exact=True).click()
    expect(page.get_by_role("heading", name="Accounts", exact=True)).to_be_visible()
    page.get_by_role("button", name="Edit", exact=True).click()
    page.get_by_label("Credential", exact=True).select_option("cred://ui-token")
    page.get_by_label("Browser Profile Id", exact=True).select_option("ui-profile")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("link", name="Sources", exact=True).click()
    expect(page.get_by_role("heading", name="Sources", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add source", exact=True).click()
    page.get_by_label("Provider", exact=True).select_option("openai")
    page.get_by_label("Model", exact=True).fill("test-model")
    page.get_by_label("Base URL", exact=True).fill(os.environ["COT_UI_UPSTREAM"])
    page.get_by_role("button", name="Continue", exact=True).click()
    page.get_by_label("Account", exact=True).select_option("ui-account")
    page.get_by_label("Quota domain", exact=True).fill("ui-quota")
    page.get_by_label("Input USD per million tokens", exact=True).fill("0.25")
    page.get_by_label("Output USD per million tokens", exact=True).fill("1.5")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("openai", exact=True).first).to_be_visible()
    page.get_by_role("button", name="Discover models", exact=True).click()
    expect(page.get_by_role("heading", name="Discovered models", exact=True)).to_be_visible()
    expect(page.get_by_text("discovered-model", exact=True)).to_be_visible()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("button", name="Validate", exact=True).click()
    page.get_by_role("button", name="Run validation", exact=True).click()
    expect(page.get_by_role("heading", name="Validation evidence", exact=True)).to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_text("Verified", exact=True))).to_contain_text("Yes")
    expect(page.get_by_role("row").filter(has=page.get_by_text("History saved", exact=True))).to_contain_text("Yes")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("button", name="Verification", exact=True).click()
    expect(page.get_by_role("dialog").get_by_text("verified", exact=True)).to_be_visible()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("button", name="openai", exact=True).click()
    expect(page.get_by_role("heading", name="Source / openai", exact=True)).to_be_visible()
    expect(page.get_by_role("dialog").get_by_text("0.25 / 1.5", exact=True)).to_be_visible()
    expect(page.get_by_role("dialog").get_by_text("verified", exact=True)).to_be_visible()
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Input tokens observed", exact=True))).to_contain_text("2")
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Estimated declared cost", exact=True))).to_contain_text("$0.000002")
    page.get_by_role("button", name="Explain eligibility", exact=True).click()
    expect(page.get_by_role("columnheader", name="Eligibility for this request", exact=True)).to_be_visible()
    page.get_by_role("button", name="Benchmark", exact=True).click()
    page.get_by_role("button", name="Run 3 samples", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("cell", name="Verified", exact=True)).to_have_count(3)
    expect(page.get_by_role("dialog").get_by_role("cell", name="Saved", exact=True)).to_have_count(3)
    expect(page.get_by_role("button", name="Run 3 samples", exact=True)).to_be_enabled()
    page.get_by_role("button", name="Close", exact=True).click()
    # A failed sample must stop the run instead of blindly consuming all three.
    benchmark_requests = []
    def failed_sample(route):
        benchmark_requests.append(route.request.url)
        route.fulfill(status=200, content_type="application/json", body='{"verified":false,"history_recorded":false}')
    page.route("**/admin/sources/openai/validate", failed_sample)
    page.get_by_role("button", name="openai", exact=True).click()
    page.get_by_role("button", name="Benchmark", exact=True).click()
    page.get_by_role("button", name="Run 3 samples", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("cell", name="Failed", exact=True)).to_have_count(1)
    expect(page.get_by_role("button", name="Run 3 samples", exact=True)).to_be_enabled()
    assert len(benchmark_requests) == 1
    page.get_by_role("button", name="Close", exact=True).click()
    page.unroute("**/admin/sources/openai/validate", failed_sample)
    # Hold a synthetic request until the UI aborts it; no upstream is contacted.
    page.evaluate("""() => {
      window.benchmarkFetch = window.fetch;
      window.heldSamples = 0;
      window.fetch = (url, options) => {
        if (String(url).endsWith('/admin/sources/openai/validate')) {
          window.heldSamples++;
          return new Promise((resolve, reject) => options.signal.addEventListener('abort', () => reject(new DOMException('Canceled', 'AbortError')), {once:true}));
        }
        return window.benchmarkFetch(url, options);
      };
    }""")
    page.get_by_role("button", name="openai", exact=True).click()
    page.get_by_role("button", name="Benchmark", exact=True).click()
    page.get_by_role("button", name="Run 3 samples", exact=True).click()
    expect(page.get_by_role("button", name="Run 3 samples", exact=True)).to_be_disabled()
    page.get_by_role("button", name="Stop samples", exact=True).click()
    expect(page.get_by_role("button", name="Run 3 samples", exact=True)).to_be_enabled()
    assert page.evaluate("window.heldSamples") == 1
    page.get_by_role("button", name="Run 3 samples", exact=True).click()
    expect(page.get_by_role("button", name="Run 3 samples", exact=True)).to_be_disabled()
    page.get_by_role("button", name="Close", exact=True).click()
    page.wait_for_timeout(100)
    assert page.evaluate("window.heldSamples") == 2
    page.evaluate("window.fetch = window.benchmarkFetch; delete window.benchmarkFetch")
    page.get_by_role("link", name="Providers", exact=True).click()
    page.get_by_role("searchbox", name="Filter providers").fill("openai")
    page.get_by_role("button", name="openai", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Accounts / sources / models", exact=True))).to_contain_text("1 / 1 / 1")
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Sources with matching generation evidence", exact=True))).to_contain_text("1 / 1")
    page.get_by_role("button", name="Explain provider eligibility", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("columnheader", name="Source / model", exact=True)).to_be_visible()
    page.get_by_role("button", name="Source details", exact=True).click()
    expect(page.get_by_role("heading", name="Source / openai", exact=True)).to_be_visible()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Overview", exact=True).click()
    expect(page.get_by_text("Sources with matching validation", exact=True).locator("xpath=following-sibling::dd[1]")).to_have_text("1")
    page.get_by_role("link", name="Credentials", exact=True).click()
    page.get_by_role("row").filter(has=page.get_by_text("cred://ui-token", exact=True)).get_by_role("button", name="Replace", exact=True).click()
    page.get_by_label("Secret value", exact=True).fill("replacement-synthetic-secret")
    page.get_by_role("button", name="Save credential", exact=True).click()
    expect(page.get_by_role("heading", name="Review credential replacement", exact=True)).to_be_visible()
    page.get_by_role("button", name="Replace credential", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    assert "replacement-synthetic-secret" not in page.content()
    page.get_by_role("link", name="Overview", exact=True).click()
    expect(page.get_by_text("Sources with matching validation", exact=True).locator("xpath=following-sibling::dd[1]")).to_have_text("0")
    page.get_by_role("link", name="Sources", exact=True).click()
    page.get_by_role("button", name="Verification", exact=True).click()
    expect(page.get_by_role("dialog").get_by_text("historical", exact=True)).to_be_visible()
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Credential version", exact=True))).to_contain_text("2")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Providers", exact=True).click()
    page.get_by_role("searchbox", name="Filter providers").fill("openai")
    page.get_by_role("button", name="openai", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Sources with matching generation evidence", exact=True))).to_contain_text("0 / 1")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Activity", exact=True).click()
    page.get_by_role("button", name="Refresh history", exact=True).click()
    expect(page.get_by_role("button", name="Refresh history", exact=True)).to_be_enabled()
    expect(page.get_by_text("explicit_stream_generation", exact=True)).to_have_count(4)
    expect(page.get_by_role("heading", name="Execution events", exact=True)).to_be_visible()
    page.get_by_label("Event source", exact=True).select_option("openai")
    page.get_by_label("Event outcome", exact=True).select_option("succeeded")
    expect(page.get_by_role("cell", name="chat / Validation", exact=True)).to_have_count(4)
    page.get_by_label("Event outcome", exact=True).select_option("failed")
    expect(page.get_by_text("No matching execution events.", exact=True)).to_be_visible()
    page.get_by_label("Event outcome", exact=True).select_option("all")
    page.get_by_role("link", name="Credentials", exact=True).click()
    page.get_by_role("button", name="Import token", exact=True).click()
    page.get_by_label("Configured source for environment import", exact=True).select_option("openai")
    page.get_by_role("button", name="Preview token", exact=True).click()
    expect(page.get_by_text("Available: Yes", exact=True)).to_be_visible()
    assert "synthetic-env-token-not-for-display" not in page.content()
    page.get_by_role("button", name="Save imported token", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("environment:openai", exact=True)).to_be_visible()
    page.get_by_role("button", name="Import token", exact=True).click()
    page.get_by_label("Import from", exact=True).select_option("codex")
    page.get_by_label("CLI session JSON file", exact=True).set_input_files({"name":"auth.json","mimeType":"application/json","buffer":b'{"tokens":{"access_token":"synthetic-cli-access","refresh_token":"never-import-refresh"}}'})
    page.get_by_role("button", name="Preview token", exact=True).click()
    expect(page.get_by_role("heading", name="Token import preview", exact=True)).to_be_visible()
    assert "synthetic-cli-access" not in page.content()
    assert "never-import-refresh" not in page.content()
    page.get_by_role("button", name="Save imported token", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("cli-export:codex", exact=True)).to_be_visible()
    page.get_by_role("link", name="Groups", exact=True).click()
    expect(page.get_by_role("heading", name="Groups", exact=True)).to_be_visible()
    page.get_by_role("button", name="Edit", exact=True).click()
    page.get_by_role("checkbox", name="openai", exact=True).check()
    page.get_by_role("checkbox", name="Require vision", exact=True).check()
    page.get_by_label("Maximum USD per million tokens", exact=True).fill("2.5")
    page.get_by_role("button", name="Add preference", exact=True).click()
    page.get_by_label("Preference 1", exact=True).select_option("lower_cost")
    page.get_by_role("button", name="Add preference", exact=True).click()
    page.get_by_label("Preference 2", exact=True).select_option("existing_subscription")
    page.get_by_label("Preference 2", exact=True).locator("..").get_by_role("button", name="Up", exact=True).click()
    expect(page.get_by_label("Preference 1", exact=True)).to_have_value("existing_subscription")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("button", name="Edit", exact=True).click()
    expect(page.get_by_role("checkbox", name="Require vision", exact=True)).to_be_checked()
    expect(page.get_by_label("Maximum USD per million tokens", exact=True)).to_have_value("2.5")
    expect(page.get_by_label("Preference 1", exact=True)).to_have_value("existing_subscription")
    expect(page.get_by_label("Preference 2", exact=True)).to_have_value("lower_cost")
    page.get_by_role("button", name="Close", exact=True).click()
    for adapter in ["claude-web", "blackbox"]:
        page.get_by_role("link", name="Providers", exact=True).click()
        page.get_by_role("searchbox", name="Filter providers").fill(adapter)
        page.get_by_role("button", name=adapter, exact=True).click()
        page.get_by_role("button", name="Add account", exact=True).click()
        page.get_by_label("ID", exact=True).fill("ui-" + adapter)
        page.get_by_label("Quota domain", exact=True).fill("ui-" + adapter)
        page.get_by_label("Browser Profile Id", exact=True).select_option("ui-profile")
        if adapter == "claude-web":
            page.get_by_role("button", name="Login with selected profile", exact=True).click()
            expect(page.get_by_role("heading", name="Browser port occupied", exact=True)).to_be_visible()
            page.get_by_role("button", name="Use running browser", exact=True).click()
            expect(page.get_by_text("Login detected for this selected profile. Review and save the account.", exact=True)).to_be_visible()
        page.get_by_role("button", name="Review changes", exact=True).click()
        page.get_by_role("button", name="Apply changes", exact=True).click()
        expect(page.get_by_role("dialog")).not_to_be_visible()
        page.get_by_role("link", name="Accounts", exact=True).click()
        row = page.get_by_role("row").filter(has=page.get_by_text("ui-" + adapter, exact=True))
        row.get_by_role("button", name="Check login", exact=True).click()
        expect(page.get_by_role("dialog").get_by_text("authenticated", exact=True)).to_be_visible()
        expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("History saved", exact=True))).to_contain_text("Yes")
        expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("Generation verified", exact=True))).to_contain_text("No")
        assert "private-organization-id" not in page.content()
        assert "private@example.test" not in page.content()
        assert "private-session-token" not in page.content()
        auth_status[adapter] = 401
        page.get_by_role("button", name="Check now", exact=True).click()
        expect(page.get_by_role("dialog").get_by_text("login_required", exact=True)).to_be_visible()
        auth_status[adapter] = 200
        page.get_by_role("button", name="Wait for login", exact=True).click()
        expect(page.get_by_role("dialog").get_by_text("authenticated", exact=True)).to_be_visible()
        for status, expected in [(403, "challenge_or_access_denied"), (429, "rate_limited"), (500, "unknown")]:
            auth_status[adapter] = status
            page.get_by_role("button", name="Check now", exact=True).click()
            expect(page.get_by_role("dialog").get_by_text(expected, exact=True)).to_be_visible()
        auth_status[adapter] = 200
        page.get_by_role("button", name="Check now", exact=True).click()
        expect(page.get_by_role("dialog").get_by_text("authenticated", exact=True)).to_be_visible()
        page.get_by_role("button", name="Close", exact=True).click()
        expect(row).to_contain_text("authenticated")
    expect(page.get_by_role("row").filter(has=page.get_by_text("ui-claude-web", exact=True))).to_contain_text("historical configuration")
    auth_status["blackbox"] = 401
    page.get_by_role("row").filter(has=page.get_by_text("ui-blackbox", exact=True)).get_by_role("button", name="Check login", exact=True).click()
    expect(page.get_by_role("dialog").get_by_text("login_required", exact=True)).to_be_visible()
    page.get_by_role("button", name="Wait for login", exact=True).click()
    expect(page.get_by_role("button", name="Wait for login", exact=True)).to_be_enabled()
    page.get_by_role("button", name="Close", exact=True).click()
    finished_checks = len(auth_requests)
    page.wait_for_timeout(5500)
    assert len(auth_requests) == finished_checks, "Closing the login dialog did not stop polling"
    assert len(browser.pages) == existing_browser_pages, "Login checks left owned browser tabs open"
    assert all(method == "GET" for _, method, _ in auth_requests)
    page.get_by_role("button", name="Account pools", exact=True).click()
    page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("openai", exact=True)).get_by_role("button", name="Edit pool", exact=True).click()
    page.get_by_label("Pool strategy", exact=True).select_option("weighted")
    page.get_by_label("Weight ui-account", exact=True).fill("3")
    page.get_by_label("Concurrency ui-account", exact=True).fill("2")
    page.get_by_role("button", name="Review pool changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("button", name="Account pools", exact=True).click()
    expect(page.get_by_role("dialog").get_by_role("row").filter(has=page.get_by_text("openai", exact=True))).to_contain_text("weighted")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Health", exact=True).click()
    expect(page.get_by_role("heading", name="Account health", exact=True)).to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_text("ui-account", exact=True))).to_contain_text("openai")
    page.get_by_role("button", name="Edit shared quota", exact=True).click()
    page.get_by_label("Shared concurrent requests", exact=True).fill("2")
    page.get_by_role("button", name="Review quota changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_text("ui-quota", exact=True))).to_contain_text("0 / 2")
    page.get_by_role("link", name="Accounts", exact=True).click()
    page.get_by_role("button", name="Add account", exact=True).click()
    page.get_by_label("Provider", exact=True).select_option("openai")
    page.get_by_label("ID", exact=True).fill("wizard-import")
    page.get_by_label("Quota domain", exact=True).fill("wizard-import")
    page.get_by_role("button", name="Import token", exact=True).click()
    page.get_by_label("Import from", exact=True).select_option("oauth")
    page.get_by_label("CLI session JSON file", exact=True).set_input_files({"name":"oauth.json","mimeType":"application/json","buffer":b'{"access_token":"wizard-private-token"}'})
    page.get_by_role("button", name="Preview token", exact=True).click()
    page.get_by_role("button", name="Save imported token", exact=True).click()
    expect(page.get_by_role("heading", name="Set up account", exact=True)).to_be_visible()
    expect(page.get_by_label("ID", exact=True)).to_have_value("wizard-import")
    assert page.get_by_label("Credential", exact=True).input_value().startswith("cred://")
    assert "wizard-private-token" not in page.content()
    page.get_by_role("button", name="Review changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_text("wizard-import", exact=True).first)).to_contain_text("Manual")
    for label in ["Credentials", "Sources", "Models", "Groups", "Routing", "Health", "Metrics", "Browsers", "Devices", "Sessions", "Configuration", "Activity", "About"]:
        page.get_by_role("link", name=label, exact=True).click()
        expect(page.get_by_role("heading", name=label, exact=True)).to_be_visible()
    page.get_by_role("link", name="Configuration", exact=True).click()
    expect(page.get_by_role("heading", name="Configuration", exact=True)).to_be_visible()
    assert "\nnull\n" not in page.locator("main").inner_text()
    page.screenshot(path=str(output / "configuration.png"), full_page=True)
    page.set_viewport_size({"width": 390, "height": 844})
    page.get_by_role("link", name="Overview", exact=True).click()
    expect(page.get_by_role("heading", name="Overview", exact=True)).to_be_visible()
    page.screenshot(path=str(output / "mobile.png"), full_page=True)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Mobile page overflows"
    assert not errors, errors
    page.get_by_role("link", name="Providers", exact=True).click()
    for cloud_provider in ["volcengine-ark", "tencent-hunyuan", "baidu-qianfan", "tencent-tokenhub", "tencent-tokenhub-sg"]:
        page.get_by_role("searchbox", name="Filter providers").fill(cloud_provider)
        page.get_by_role("button", name=cloud_provider, exact=True).click()
        expect(page.get_by_role("heading", name=cloud_provider, exact=True)).to_be_visible()
        page.get_by_role("dialog").get_by_role("button", name="Add source", exact=True).click()
        expect(page.get_by_label("Provider", exact=True)).to_have_value(cloud_provider)
        page.get_by_label("Model", exact=True).fill("synthetic-model-id")
        page.get_by_role("button", name="Continue", exact=True).click()
        expect(page.get_by_label("Source type", exact=True)).to_have_value("cloud_api")
        expect(page.get_by_role("checkbox", name="Enabled", exact=True).first).not_to_be_checked()
        page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Sources", exact=True).click()
    page.get_by_role("button", name="Add source", exact=True).click()
    page.get_by_label("Provider", exact=True).select_option("openai")
    page.get_by_label("Model", exact=True).fill("bulk-model")
    page.get_by_label("Base URL", exact=True).fill(os.environ["COT_UI_UPSTREAM"])
    page.get_by_role("button", name="Continue", exact=True).click()
    page.get_by_label("ID", exact=True).first.fill("bulk-source")
    page.get_by_label("Account", exact=True).select_option("ui-account")
    page.get_by_label("Quota domain", exact=True).fill("ui-quota")
    page.get_by_label("Shared quota concurrency", exact=True).fill("2")
    page.get_by_role("button", name="Review changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("link", name="Models", exact=True).click()
    page.get_by_role("button", name="Select filtered models", exact=True).click()
    expect(page.get_by_text("2 models selected, including selections outside the current filter.", exact=True)).to_be_visible()
    page.get_by_role("button", name="Edit selected models", exact=True).click()
    page.get_by_label("Models enabled", exact=True).select_option("false")
    page.get_by_label("Models Auto approval", exact=True).select_option("false")
    page.get_by_label("Models tier", exact=True).select_option("silver")
    page.get_by_role("button", name="Review model changes", exact=True).click()
    expect(page.get_by_role("dialog").get_by_text("A rated tier requires a rating basis.", exact=True)).to_be_visible()
    page.get_by_label("Models rating basis", exact=True).fill("Synthetic UI fixture rating only")
    page.get_by_role("button", name="Review model changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_role("cell", name="Disabled", exact=True)).to_have_count(2)
    expect(page.get_by_role("cell", name="Not approved", exact=True)).to_have_count(2)
    page.get_by_label("Filter models", exact=True).fill("bulk-model")
    page.get_by_role("button", name="Select filtered models", exact=True).click()
    page.get_by_role("button", name="Edit selected models", exact=True).click()
    page.get_by_label("Models enabled", exact=True).select_option("true")
    page.get_by_label("Models Auto approval", exact=True).select_option("true")
    page.get_by_role("button", name="Review model changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_role("checkbox", name="Select model bulk-source/bulk-model", exact=True))).to_contain_text("Approved")
    expect(page.get_by_role("row").filter(has=page.get_by_role("checkbox", name="Select model openai/test-model", exact=True))).to_contain_text("Disabled")
    expect(page.get_by_role("row").filter(has=page.get_by_role("checkbox", name="Select model openai/test-model", exact=True))).to_contain_text("Not approved")
    for search_term, result_label, expected_heading in [
        ("tencent-hunyuan", "tencent-hunyuan", "tencent-hunyuan"),
        ("bulk-source", "bulk-source", "Source / bulk-source"),
        ("auto", "auto", "Edit Group / auto"),
        ("ui-account", "UI test account", "Edit Account / ui-account"),
        ("bulk-model", "bulk-model · bulk-source", "Edit selected models"),
        ("ui-profile", "ui-profile", "Edit Browser Profile / ui-profile"),
        ("cred://ui-token", "cred://ui-token", "Replace credential"),
    ]:
        page.get_by_role("searchbox", name="Search everything", exact=True).fill(search_term)
        page.get_by_role("button", name=result_label, exact=True).click()
        expect(page.get_by_role("heading", name=expected_heading, exact=True)).to_be_visible()
        page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("searchbox", name="Search everything", exact=True).fill("android")
    page.get_by_role("button", name="Android device settings", exact=True).click()
    expect(page.get_by_role("heading", name="Devices", exact=True)).to_be_visible()
    page.get_by_role("button", name="Check device", exact=True).click()
    expect(page.get_by_text("Needs attention", exact=True)).to_be_visible()
    expect(page.get_by_role("heading", name="App providers", exact=True)).to_be_visible()
    page.get_by_role("link", name="Browsers", exact=True).click()
    page.get_by_role("button", name="Owned processes", exact=True).click()
    expect(page.get_by_text("No browser processes launched by this gateway.", exact=True)).to_be_visible()
    page.get_by_role("button", name="Close", exact=True).click()
    owned_state = {"state":"running", "stops":0}
    def synthetic_owned_processes(route):
        if route.request.url.endswith("/synthetic-launch/stop"):
            assert route.request.method == "POST"
            assert route.request.post_data_json == {"confirm": True}
            owned_state["stops"] += 1
            owned_state["state"] = "stopped"
            route.fulfill(status=200, content_type="application/json", body='{"status":"stop_requested"}')
        else:
            assert route.request.method == "GET"
            route.fulfill(status=200, content_type="application/json", body=json.dumps([{"id":"synthetic-launch","profile":"ui-profile","pid":12345,"started_at":"2026-09-10T00:00:00Z","state":owned_state["state"]}]))
    page.route("**/admin/browser_profiles/processes**", synthetic_owned_processes)
    page.get_by_role("button", name="Owned processes", exact=True).click()
    page.get_by_role("button", name="Stop", exact=True).click()
    expect(page.get_by_role("heading", name="Stop owned browser", exact=True)).to_be_visible()
    assert owned_state["stops"] == 0
    page.get_by_role("button", name="Cancel", exact=True).click()
    page.get_by_role("button", name="Stop", exact=True).click()
    page.get_by_role("button", name="Stop owned process", exact=True).click()
    expect(page.get_by_role("cell", name="stopped", exact=True)).to_be_visible()
    assert owned_state["stops"] == 1
    page.get_by_role("button", name="Close", exact=True).click()
    page.unroute("**/admin/browser_profiles/processes**", synthetic_owned_processes)
    page.get_by_role("button", name="Launch provider", exact=True).click()
    expect(page.get_by_label("Provider to open", exact=True)).to_have_value("openai")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Configuration", exact=True).click()
    page.get_by_role("button", name="Runtime", exact=True).click()
    queued = page.get_by_label("Max Queued", exact=True)
    queued.fill(str(int(queued.input_value()) + 1))
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("button", name="Version history", exact=True).click()
    expect(page.get_by_role("heading", name="Configuration history", exact=True)).to_be_visible()
    page.get_by_role("button", name="Compare / restore", exact=True).first.click()
    expect(page.get_by_text("Restoring creates a new revision.", exact=False)).to_be_visible()
    page.get_by_role("button", name="Restore", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    assert not errors, errors
    browser.close()
print("UI smoke passed: credential redaction, account binding, source creation, group membership, preview/apply, navigation and responsive layout.")
