"""Browser smoke test against scripts/ui_fixture.py on port 18317."""
from pathlib import Path
import os
from playwright.sync_api import sync_playwright, expect

output = Path(__file__).resolve().parents[1] / ".clash-tokens" / "ui-artifacts"
output.mkdir(parents=True, exist_ok=True)
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    errors = []
    page.on("pageerror", lambda error: (errors.append(str(error)), print("Browser error:", error)))
    page.goto("http://127.0.0.1:18317")
    page.wait_for_load_state("networkidle")
    expect(page.get_by_role("heading", name="Your sources, one place.")).to_be_visible()
    page.get_by_label("Admin key", exact=True).fill("ui-test-admin-key-123456789")
    page.get_by_role("button", name="Connect", exact=True).last.click()
    expect(page.get_by_role("heading", name="Overview", exact=True)).to_be_visible()
    page.screenshot(path=str(output / "overview.png"), full_page=True)
    page.get_by_role("link", name="Providers", exact=True).click()
    expect(page.get_by_role("heading", name="Providers", exact=True)).to_be_visible()
    page.get_by_role("searchbox", name="Filter providers").fill("openai")
    page.get_by_role("button", name="openai", exact=True).click()
    expect(page.get_by_role("heading", name="openai", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add account", exact=True).click()
    page.get_by_label("ID", exact=True).fill("ui-account")
    page.get_by_label("Display Name", exact=True).fill("UI test account")
    page.get_by_label("Quota domain", exact=True).fill("ui-quota")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("link", name="Accounts", exact=True).click()
    expect(page.get_by_text("UI test account", exact=True)).to_be_visible()
    page.get_by_role("link", name="Browsers", exact=True).click()
    page.get_by_role("button", name="Add profile", exact=True).click()
    page.get_by_label("ID", exact=True).fill("ui-profile")
    page.get_by_role("button", name="Review changes", exact=True).click()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("ui-profile", exact=True)).to_be_visible()
    page.get_by_role("link", name="Credentials", exact=True).click()
    expect(page.get_by_role("heading", name="Credentials", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add credential", exact=True).click()
    page.get_by_label("Credential ID", exact=True).fill("ui-token")
    page.get_by_label("Secret value", exact=True).fill("synthetic-secret-not-for-display")
    page.get_by_role("button", name="Save credential", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("cred://ui-token", exact=True)).to_be_visible()
    assert "synthetic-secret-not-for-display" not in page.content(), "Credential echoed into DOM"
    page.get_by_role("button", name="Import export", exact=True).click()
    page.get_by_label("CSV or JSON file", exact=True).set_input_files({"name":"selected.csv","mimeType":"text/csv","buffer":b"name,url,username,password\nSelected,https://example.com,synthetic-login,synthetic-import-secret\nSkipped,https://example.org,other-user,other-secret\n"})
    page.get_by_role("button", name="Preview entries", exact=True).click()
    expect(page.get_by_role("heading", name="Select credentials to import", exact=True)).to_be_visible()
    assert "synthetic-import-secret" not in page.content()
    assert "synthetic-login" not in page.content()
    page.get_by_role("checkbox", name="Import entry 1", exact=True).check()
    page.get_by_role("button", name="Import selected", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("selected-export", exact=True)).to_have_count(1)
    assert "synthetic-import-secret" not in page.content()
    page.get_by_role("link", name="Accounts", exact=True).click()
    expect(page.get_by_role("heading", name="Accounts", exact=True)).to_be_visible()
    page.get_by_role("button", name="Edit", exact=True).click()
    page.get_by_label("Credential", exact=True).select_option("cred://ui-token")
    page.get_by_label("Browser Profile Id", exact=True).select_option("ui-profile")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    page.get_by_role("link", name="Sources", exact=True).click()
    expect(page.get_by_role("heading", name="Sources", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add source", exact=True).click()
    page.get_by_label("Provider", exact=True).select_option("openai")
    page.get_by_label("Model", exact=True).fill("test-model")
    page.get_by_label("Base URL", exact=True).fill(os.environ["COT_UI_UPSTREAM"])
    page.get_by_role("button", name="Continue", exact=True).click()
    page.get_by_label("Account", exact=True).select_option("ui-account")
    page.get_by_label("Quota domain", exact=True).fill("ui-quota")
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("openai", exact=True).first).to_be_visible()
    page.get_by_role("button", name="Discover models", exact=True).click()
    expect(page.get_by_role("heading", name="Discovered models", exact=True)).to_be_visible()
    expect(page.get_by_text("discovered-model", exact=True)).to_be_visible()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("button", name="Validate", exact=True).click()
    page.get_by_role("button", name="Run validation", exact=True).click()
    expect(page.get_by_role("heading", name="Validation evidence", exact=True)).to_be_visible()
    expect(page.get_by_role("row").filter(has=page.get_by_text("Verified", exact=True))).to_contain_text("Yes")
    expect(page.get_by_role("row").filter(has=page.get_by_text("History saved", exact=True))).to_contain_text("Yes")
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("link", name="Activity", exact=True).click()
    page.get_by_role("button", name="Refresh history", exact=True).click()
    expect(page.get_by_text("explicit_stream_generation", exact=True)).to_be_visible()
    page.get_by_role("link", name="Credentials", exact=True).click()
    page.get_by_role("button", name="Import token", exact=True).click()
    page.get_by_label("Configured source for environment import", exact=True).select_option("openai")
    page.get_by_role("button", name="Preview token", exact=True).click()
    expect(page.get_by_text("Available: Yes", exact=True)).to_be_visible()
    assert "synthetic-env-token-not-for-display" not in page.content()
    page.get_by_role("button", name="Save imported token", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("environment:openai", exact=True)).to_be_visible()
    page.get_by_role("button", name="Import token", exact=True).click()
    page.get_by_label("Import from", exact=True).select_option("codex")
    page.get_by_label("CLI session JSON file", exact=True).set_input_files({"name":"auth.json","mimeType":"application/json","buffer":b'{"tokens":{"access_token":"synthetic-cli-access","refresh_token":"never-import-refresh"}}'})
    page.get_by_role("button", name="Preview token", exact=True).click()
    expect(page.get_by_role("heading", name="Token import preview", exact=True)).to_be_visible()
    assert "synthetic-cli-access" not in page.content()
    assert "never-import-refresh" not in page.content()
    page.get_by_role("button", name="Save imported token", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    expect(page.get_by_text("cli-export:codex", exact=True)).to_be_visible()
    page.get_by_role("link", name="Groups", exact=True).click()
    expect(page.get_by_role("heading", name="Groups", exact=True)).to_be_visible()
    page.get_by_role("button", name="Edit", exact=True).click()
    page.get_by_role("checkbox", name="openai", exact=True).check()
    page.get_by_role("button", name="Review changes", exact=True).click()
    expect(page.get_by_role("heading", name="Review changes", exact=True)).to_be_visible()
    page.get_by_role("button", name="Apply changes", exact=True).click()
    expect(page.get_by_role("dialog")).not_to_be_visible()
    for label in ["Credentials", "Sources", "Models", "Groups", "Routing", "Health", "Metrics", "Browsers", "Devices", "Sessions", "Configuration", "Activity", "About"]:
        page.get_by_role("link", name=label, exact=True).click()
        expect(page.get_by_role("heading", name=label, exact=True)).to_be_visible()
    page.get_by_role("link", name="Configuration", exact=True).click()
    expect(page.get_by_role("heading", name="Configuration", exact=True)).to_be_visible()
    assert "\nnull\n" not in page.locator("main").inner_text()
    page.screenshot(path=str(output / "configuration.png"), full_page=True)
    page.set_viewport_size({"width": 390, "height": 844})
    page.get_by_role("link", name="Overview", exact=True).click()
    expect(page.get_by_role("heading", name="Overview", exact=True)).to_be_visible()
    page.screenshot(path=str(output / "mobile.png"), full_page=True)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Mobile page overflows"
    assert not errors, errors
    browser.close()
print("UI smoke passed: credential redaction, account binding, source creation, group membership, preview/apply, navigation and responsive layout.")
